services:
  db:
    image: postgres:14
    container_name: pastebin_db
    restart: always
    environment:
      POSTGRES_USER: pastebin_user
      POSTGRES_PASSWORD: Radeng4u*
      POSTGRES_DB: pastebin
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
